# version: '3.8'  # Убрано для совместимости с новыми версиями Docker Compose

services:
  postgres:
    image: postgres:15-alpine
    container_name: telebot_postgres
    env_file:
      - /etc/telebot/env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"  # Закрыт для безопасности, доступ только внутри сети
    restart: unless-stopped
    networks:
      - telebot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U telebot_user -d telebot"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: telebot_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./nginx/ssl:/etc/ssl:ro
      - ./logs/nginx:/var/log/nginx
      - /dev/null:/etc/nginx/conf.d/default.conf:ro  # Отключить дефолтную конфигурацию
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    command: /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
    depends_on:
      bot:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - telebot_network

  bot:
    build: .
    container_name: telebot_app
    env_file:
      - /etc/telebot/env  # Все переменные берутся из безопасного файла
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - telebot_network
    volumes:
      - ./logs:/app/logs
    expose:
      - "8000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  telebot_network:
    driver: bridge
